/* Generated by configure */
#include <dwrite.h>
#include <d2d1.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    IDWriteFactory *factory = 0;
    DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, __uuidof(IDWriteFactory),
                        (IUnknown **)(&factory));
    /* END TEST */
    return 0;
}
