/* Generated by configure */
#include <dwrite_2.h>
#include <d2d1.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    IUnknown *factory = 0;
    (void)(size_t(DWRITE_E_NOCOLOR) + sizeof(IDWriteFontFace2));
    DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, __uuidof(IDWriteFactory2),
                        &factory);
    /* END TEST */
    return 0;
}
